#version: '3.8'

services:
  web:
    build: .
    container_name: mrbs_web
    volumes:
      - ./mrbs:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mrbs_db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: mrbs
      MYSQL_USER: mrbs_user
      MYSQL_PASSWORD: my_mrbs_password
    volumes:
      - db_data:/var/lib/mysql
      - ./tables.my.sql:/docker-entrypoint-initdb.d/tables.my.sql

volumes:
  db_data:
